-- VoltFlow V8.6.6 Security Hardening
-- Run once in Supabase SQL Editor.

create table if not exists public.quote_attempts (
  id uuid primary key default gen_random_uuid(),
  ip_hash text not null,
  email_hash text,
  phone_hash text,
  country text,
  user_agent text,
  accepted boolean not null default false,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists quote_attempts_ip_created_idx on public.quote_attempts (ip_hash, created_at desc);
create index if not exists quote_attempts_email_created_idx on public.quote_attempts (email_hash, created_at desc);
create index if not exists quote_attempts_phone_created_idx on public.quote_attempts (phone_hash, created_at desc);
create index if not exists quote_attempts_created_idx on public.quote_attempts (created_at desc);

create table if not exists public.security_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','low','medium','high','critical')),
  route text,
  country text,
  ip_hash text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_events_created_idx on public.security_events (created_at desc);
create index if not exists security_events_type_created_idx on public.security_events (event_type, created_at desc);
create index if not exists security_events_severity_created_idx on public.security_events (severity, created_at desc);

alter table public.quote_attempts enable row level security;
alter table public.security_events enable row level security;

-- Browser users never write these tables. The server-side service role logs events.
revoke all on public.quote_attempts from anon, authenticated;
revoke all on public.security_events from anon;

grant select on public.quote_attempts to authenticated;
grant select on public.security_events to authenticated;

-- Reuse the existing public.is_admin() SECURITY DEFINER function.
drop policy if exists "Admins can read quote attempts" on public.quote_attempts;
create policy "Admins can read quote attempts"
on public.quote_attempts for select to authenticated
using (public.is_admin());

drop policy if exists "Admins can read security events" on public.security_events;
create policy "Admins can read security events"
on public.security_events for select to authenticated
using (public.is_admin());

-- Direct anonymous lead inserts are no longer needed after /api/quote is deployed.
-- This removes common policy names used by earlier releases. Review Policies in the dashboard
-- and remove any other anon INSERT policy on public.leads.
drop policy if exists "Public can submit leads" on public.leads;
drop policy if exists "Anyone can submit leads" on public.leads;
drop policy if exists "anon_insert_leads" on public.leads;
drop policy if exists "Allow public lead submissions" on public.leads;

-- Keep authenticated admin access intact through your existing admin policies.

-- Optional cleanup helper: run periodically or schedule externally.
create or replace function public.purge_old_security_logs()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.quote_attempts where created_at < now() - interval '30 days';
  delete from public.security_events
  where created_at < now() - interval '30 days'
    and severity in ('info','low','medium');
  delete from public.security_events
  where created_at < now() - interval '365 days'
    and severity in ('high','critical');
end;
$$;
revoke all on function public.purge_old_security_logs() from public;

comment on table public.quote_attempts is 'Hashed quote request rate-limit and abuse records. No raw IP addresses are stored.';
comment on table public.security_events is 'Security monitoring events generated by VoltFlow server endpoints.';
