window.VOLTFLOW_COMPANY = Object.freeze({
  id: "blue-bear-electric",
  companyName: "Blue Bear Electric",
  displayName: "Blue Bear Electric",
  platformName: "VoltFlow",
  tagline: "Powering solutions. Delivering excellence.",
  phone: "760-234-8306",
  email: "info@bluebearelectric.com",
  website: "https://bluebearelectric.com",
  licenseNumber: "1141313",
  licenseLabel: "CA License #1141313",
  serviceArea: "Imperial County, California",
  primaryColor: "#061b35",
  accentColor: "#ffc400",
  secondaryColor: "#1479e8",
  logoPrimary: "assets/branding/blue-bear/logo-transparent-hd.png",
  introLogo: "assets/branding/blue-bear/logo-cinematic-wide.png",
  logoMark: "assets/branding/blue-bear/logo-mark.png",
  documentLogo: "assets/branding/blue-bear/document-logo.png",
  watermarkDark: "assets/branding/blue-bear/watermark-dark.png",
  watermarkPrint: "assets/branding/blue-bear/watermark-print.png",
  publicWatermarkOpacity: 0.065,
  documentWatermarkOpacity: 0.055
});