(function(){
  const $=(s,root=document)=>root.querySelector(s);
  const $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  let mode='proposal';
  const labels={proposal:'Proposal Draft',scope:'Scope of Work',estimate:'Estimate Plan',email:'Customer Email',safety:'Safety / JSA',troubleshoot:'Troubleshooting Plan',maintenance:'Maintenance PM Plan',inspection:'Inspection Report'};
  function projectContext(){
    return {
      title:$('[data-ws-title]')?.textContent?.trim()||'',
      meta:$('[data-ws-meta]')?.textContent?.trim()||'',
      notes:$('[data-ws-notes]')?.textContent?.trim()||'',
      items:$$('[data-estimate-list] .line-table > div').map(r=>r.textContent.trim()).filter(Boolean)
    };
  }
  function buildDraft(d){
    const header=`BLUE BEAR ELECTRIC\nCA License #1141313 | OSHA Certified | Bonded & Insured | Union Contractor\n\n${labels[mode].toUpperCase()}\n`;
    const base=`Customer / Company: ${d.customer||'Customer TBD'}\nProject / Equipment: ${d.project||'Project TBD'}\nService Type: ${d.service||'Electrical'}\nLocation: ${d.location||'Service Area TBD'}\n\nNotes:\n${d.notes||'No notes entered yet.'}\n`;
    const estimateItems=d.items?.length?`\nCurrent Estimate Items:\n${d.items.map(x=>'- '+x).join('\n')}\n`:'';
    const blocks={
proposal:`${header}\n${base}${estimateItems}\nExecutive Summary:\nBlue Bear Electric will provide professional electrical services for the project listed above, including planning, coordination, installation, troubleshooting, documentation, and closeout support as required by field conditions.\n\nProposed Scope:\n- Review existing site conditions and confirm customer requirements.\n- Coordinate safe work access, shutdown windows, and required clearances.\n- Provide labor, tools, equipment, and standard installation practices for the selected service type.\n- Complete work in a clean, professional manner with project documentation.\n- Provide before/during/after photos when applicable.\n\nAssumptions:\n- Final pricing depends on site walk, material availability, and customer-approved scope.\n- Permits, utility coordination, and after-hours work may affect schedule and cost.\n\nNext Steps:\n1. Confirm site visit or final scope.\n2. Approve estimate.\n3. Schedule work.\n4. Complete installation/service.\n5. Issue closeout documentation and invoice.`,
scope:`${header}\n${base}\nScope of Work:\n1. Site verification and safety review.\n2. Identify existing electrical equipment, service rating, panel schedule, grounding, disconnecting means, and work area limitations.\n3. Perform requested electrical installation, troubleshooting, maintenance, or repair.\n4. Label new or modified equipment where applicable.\n5. Clean work area and provide project photos.\n6. Document findings, recommendations, and remaining customer action items.\n\nExclusions:\n- Hidden damage not visible during initial review.\n- Utility-side work unless specifically included.\n- Engineering, permits, or third-party inspections unless listed.`,
estimate:`${header}\n${base}${estimateItems}\nEstimate Planning Structure:\nMaterials:\n- Panels / breakers / disconnects / conduit / wire / fittings as required.\n- Specialty equipment based on field verification.\n\nLabor:\n- Site preparation and LOTO coordination.\n- Installation or troubleshooting.\n- Testing, cleanup, and documentation.\n\nEquipment / Rentals:\n- Lift, trenching, specialty test equipment, or jobsite support if required.\n\nRecommended Pricing Notes:\n- Separate labor and material line items.\n- Add contingency for unknown existing conditions.\n- Add after-hours premium for shutdown or emergency work.`,
email:`Subject: Blue Bear Electric - ${d.project||'Project Update'}\n\nHello ${d.customer||''},\n\nThank you for reaching out to Blue Bear Electric. Based on the information provided for ${d.project||'your project'}, we are preparing the next steps and will confirm the scope, schedule, and any required site details.\n\nSummary:\n${d.notes||'We will review the project details and follow up with a professional recommendation.'}\n\nPlease send any additional photos, site access details, or preferred scheduling windows.\n\nThank you,\nBlue Bear Electric\n760-234-8306`,
safety:`${header}\n${base}\nSafety / JSA Notes:\nHazards to Review:\n- Energized electrical equipment.\n- Arc flash and shock exposure.\n- LOTO requirements.\n- Working around panels, switchgear, conductors, batteries, solar DC, or elevated work.\n- Vehicle, pedestrian, and jobsite access hazards.\n\nControls:\n- Verify qualified personnel and PPE.\n- Establish work boundaries.\n- Perform LOTO where required.\n- Verify absence of voltage before contact.\n- Use proper tools and test equipment.\n- Document hazards, photos, and customer notifications.`,
troubleshoot:`${header}\n${base}\nTroubleshooting Plan:\n1. Interview customer/operator and capture symptoms.\n2. Verify equipment nameplate, voltage, current, breaker/fuse sizes, and control power.\n3. Inspect for obvious damage, heat, loose terminations, moisture, burnt smell, nuisance trips, and alarms.\n4. Check source power, load side conditions, control circuit, interlocks, and grounding.\n5. Use appropriate meter/test equipment and document readings.\n6. Isolate likely causes and recommend corrective action.\n7. Upload photos and notes to project record.\n\nPossible Causes to Evaluate:\n- Loose/failed termination, overload, failed breaker/fuse, bad control circuit, failed contactor/relay, damaged conductor, equipment fault, or utility/source issue.`,
maintenance:`${header}\n${base}\nPreventive Maintenance Plan:\n- Review drawings, equipment labels, and prior history.\n- Inspect enclosures, disconnects, panels, terminations, grounding, seals, fans/filters, and signs of heat or contamination.\n- Torque/check terminations when permitted by manufacturer and procedure.\n- Clean debris and verify covers/deadfronts.\n- Perform IR scan under load when applicable.\n- Record deficiencies, photos, and recommended repairs.\n- Provide closeout checklist and customer report.`,
inspection:`${header}\n${base}\nInspection Report Draft:\nInspection Summary:\nBlue Bear Electric inspected the listed project/equipment and documented visible conditions, concerns, and recommended actions.\n\nFindings:\n- Finding 1: TBD\n- Finding 2: TBD\n- Finding 3: TBD\n\nSeverity:\n- Normal / Monitor / Repair Recommended / Urgent\n\nRecommendations:\n- Correct deficiencies found during inspection.\n- Schedule repairs or follow-up testing as needed.\n- Maintain photo documentation and closeout records.\n\nPhotos:\nAttach relevant before/during/after, thermal, or equipment photos from the project gallery.`
    };
    return blocks[mode]||blocks.proposal;
  }
  function getFormData(){const f=$('[data-ai-form]'); const fd=new FormData(f); const p=projectContext(); return {customer:fd.get('customer'),project:fd.get('project')||p.title,service:fd.get('service'),location:fd.get('location')||p.meta,notes:fd.get('notes')||p.notes,items:p.items};}
  function saveLocal(text){const drafts=JSON.parse(localStorage.getItem('bb_ai_drafts')||'[]'); drafts.unshift({mode,title:labels[mode],text,created_at:new Date().toISOString()}); localStorage.setItem('bb_ai_drafts',JSON.stringify(drafts.slice(0,25))); renderDrafts();}
  function renderDrafts(){const box=$('[data-ai-drafts]'); if(!box) return; const drafts=JSON.parse(localStorage.getItem('bb_ai_drafts')||'[]'); box.innerHTML=drafts.length?drafts.map((d,i)=>`<div class="activity-item ai-draft" data-draft-index="${i}"><span class="activity-dot"></span><div><p><b>${esc(d.title)}</b></p><small>${new Date(d.created_at).toLocaleString()}</small><p>${esc(d.text).slice(0,180)}...</p></div></div>`).join(''):'<p class="small">No saved drafts yet.</p>';}
  document.addEventListener('click',e=>{
    const m=e.target.closest('[data-ai-mode]'); if(m){mode=m.dataset.aiMode; $$('.ai-mode').forEach(b=>b.classList.toggle('active',b===m)); const t=$('[data-ai-output-title]'); if(t)t.textContent=labels[mode];}
    if(e.target.matches('[data-ai-use-project]')){const p=projectContext(); const f=$('[data-ai-form]'); if(f){f.project.value=p.title||f.project.value; f.location.value=p.meta||f.location.value; f.notes.value=p.notes||f.notes.value;}}
    if(e.target.matches('[data-ai-copy]')){const out=$('[data-ai-global-output]'); if(out?.value) navigator.clipboard?.writeText(out.value);}
    if(e.target.matches('[data-ai-save-draft]')){const out=$('[data-ai-global-output]'); if(out?.value) saveLocal(out.value);}
    if(e.target.matches('[data-ai-clear-drafts]')){localStorage.removeItem('bb_ai_drafts'); renderDrafts();}
    const draft=e.target.closest('.ai-draft'); if(draft){const drafts=JSON.parse(localStorage.getItem('bb_ai_drafts')||'[]'); const d=drafts[Number(draft.dataset.draftIndex)]; const out=$('[data-ai-global-output]'); if(d&&out){out.value=d.text; mode=d.mode||mode;}}
  });
  document.addEventListener('submit',e=>{if(e.target.matches('[data-ai-form]')){e.preventDefault(); const text=buildDraft(getFormData()); const out=$('[data-ai-global-output]'); if(out) out.value=text;}});
  document.addEventListener('DOMContentLoaded',renderDrafts);
})();
